services:
  - type: web
    name: aviator-web
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: base_de_datos_aviator
          property: connectionString
databases:
  - name: base_de_datos_aviator
